server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:ordenes_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  services:
    auth-url: http://localhost:8081
    productos-url: http://localhost:8082
